// <auto-generated />
namespace Garage_MVC_WEB_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TableClients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableClients));
        
        string IMigrationMetadata.Id
        {
            get { return "202201091337002_TableClients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
